version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
    environment:
      - NODE_ENV=production
    networks:
      - coding-playground

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    networks:
      - coding-playground

networks:
  coding-playground:
    driver: bridge