FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    python3-tk \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install numpy pandas matplotlib pillow

WORKDIR /code

CMD ["python", "main.py"]
